Steps one & two added for the atDude Tutorial
atsign-foundation/atsign.dev-3.0 pull request #127
Opened 2022-08-29 18:48 UTC by CurtlyCritchlow

**- What I did**

1. Added steps one and two to the atDude tutorial.
2. Converted the old tutorials to drafts. The draft tutorials would be removed completely after I recycle its contents.

**- How I did it**
Created the markdown files and assets for steps one and two of the atDude tutorial. 
**- How to verify it**
run `npm run start` and navigate to the atDude tutorial
**- Description for the changelog**

1. Added steps one and two to the atDude tutorial.
2. Converted the old tutorials to drafts

2022-08-29 18:54 UTC, JeremyTubongbanua requested changes
2 things:
1. SEO descriptions 
2. The folder name reflects the url and we like to use dashes (-) instead of underscores (_)So instead of "1_introduction" please make it "1-introduction"

Awesome work so far

2022-08-29 18:54 UTC, JeremyTubongbanua commented on content_dev/docs/tutorials/at-dude/1_introduction/index.md
> +  Documentation
Small thing- please add a description for SEO purposes

2022-08-29 18:54 UTC, JeremyTubongbanua commented on content_dev/docs/tutorials/at-dude/2_getting_started/index.md
> +  Documentation
Here too

2022-08-29 19:10 UTC, CurtlyCritchlow commented on content_dev/docs/tutorials/at-dude/1_introduction/index.md
> +  Documentation
done

2022-08-29 19:11 UTC, CurtlyCritchlow commented on content_dev/docs/tutorials/at-dude/2_getting_started/index.md
> +  Documentation
done

2022-08-29 19:15 UTC, JeremyTubongbanua approved these changes, later dismissed

2022-09-06 15:26 UTC, TylerTrott approved these changes

2022-09-06 15:28 UTC, merged