refactor: contribute section
atsign-foundation/atsign.dev-3.0 pull request #139
Opened 2022-09-14 00:25 UTC by XavierChanth

**- What I did**

Nested the current contribute section into "this-site" so that the atmospherePro contribution guidelines can sit parallel.

**- How I did it**

Local changes.

**- How to verify it**

**- Description for the changelog**
refactor: contribute section

2022-09-16 13:17 UTC, JeremyTubongbanua requested changes
Hey @XavierChanth

See image below - was this the intention?
<img width="359" alt="Screen Shot 2022-09-16 at 9 14 14 AM" src="https://user-images.githubusercontent.com/79019866/190647496-71915b00-59f2-49a0-a620-2b59e9a80518.png">

2022-09-16 13:23 UTC, XavierChanth commented
Yes, since we will add atmospherePro in parallel to it, maybe we can shorten it to just "This site"

2022-09-16 18:22 UTC, JeremyTubongbanua approved these changes, later dismissed

2022-09-23 13:38 UTC, XavierChanth commented
Welp, this did not rebase cleanly... I will reopen

2022-09-23 13:38 UTC, closed without merging