refactor: updated docs
atsign-foundation/atsign.dev-3.0 pull request #154
Opened 2022-09-23 09:14 UTC by purnimavenkatasubbu

**- What I did**
Updated the content as mentioned in the document 
https://docs.google.com/document/d/1DGj49jVsAqr4gS5wN6HlcEyWT9M-tHEF--MsW6_hyjo/edit

**- How I did it**

**- How to verify it**

**- Description for the changelog**

2022-09-23 15:12 UTC, TylerTrott approved these changes, later dismissed

2022-09-26 06:24 UTC, murali-shris commented on content/docs/sdk/flutter/at_client_manager.md
> +SyncService syncs local secondary and cloud secondary.
we can mention client app/mobile app instead of local secondary.
replace cloud secondary with remote secondary server

2022-09-28 11:46 UTC, murali-shris approved these changes, later dismissed

2022-09-28 13:52 UTC, XavierChanth requested changes
Looks great! Thanks for the work!

I requested some minor grammatical changes for clarity.

2022-09-28 13:52 UTC, XavierChanth commented on content/docs/sdk/flutter/at_client_manager.md
> + The setCurrentAtSign method accepts the following arguments: currentAtSign, namespace and the preferences. The currentAtsign argument accepts an atsign , namespace accepts the namespace of the app a
atSign should remain with capital S when referring to the product or string identifier for it.

2022-09-28 13:52 UTC, XavierChanth commented on content/docs/sdk/flutter/at_client_manager.md
> +Notification service gives back stream of notifications from the server to the subscribing client.
`gives back` -> `gives back a`

2022-09-28 13:52 UTC, XavierChanth commented on content/docs/sdk/flutter/at_client_manager.md
> +  If client app's changes are ahead, pushes the changes to the remote secondary.
`If client` -> `If the client`

2022-09-28 13:52 UTC, XavierChanth commented on content/docs/sdk/flutter/at_client_manager.md
> +  If remote secondary is ahead, pulls the changes to the client app.
`If remote` -> `If the remote`

2022-09-28 13:52 UTC, XavierChanth commented on content/docs/sdk/flutter/at_client_manager.md
> +  If client app's changes are ahead, pushes the changes to the remote secondary.
`, pushes` -> `, it pushes`

2022-09-28 13:52 UTC, XavierChanth commented on content/docs/sdk/flutter/at_client_manager.md
> +  If remote secondary is ahead, pulls the changes to the client app.
`, pulls` -> `, it pulls`

2022-09-28 13:52 UTC, XavierChanth commented on content/docs/sdk/flutter/key_basics.md
> +CCD (Cascade delete) compliments the TTR functionality by allowing the owner of the key to decide if the cached key has to be deleted upon the deletion of the original key. CCD accepts a boolean valu
`Setting false...` -> `Setting it to false results in the cached key remaining, even after the original key is deleted.`

2022-09-28 13:52 UTC, XavierChanth commented on content/docs/sdk/flutter/key_basics.md
> +**atProtocol CRUD operations**
`atProtocol` -> `atPlatform`

2022-09-28 13:52 UTC, XavierChanth commented on content/docs/sdk/flutter/key_basics.md
> +SDK of atProtocol exposes two methods to create the data. They are:
`SDK of atProtocol` -> `atPlatform SDK`

2022-09-28 13:52 UTC, XavierChanth commented on content/docs/sdk/flutter/introduction.md
> +- **AtClientPreference** - object used to configure preferences in your atPlatform application such as the namespace, hivestoragepath, or maxdatasize.
`atsign` -> `atSign`
`hivestoragepath` -> `storage path for the hive database`
`maxdatasize` -> `maximum data size`

If they aren't going to remain as camel case arguments, I believe it's best we describe them fully.

2022-09-28 14:06 UTC, purnimavenkatasubbu commented
@XavierChanth Addressed the review comments and pushed the changes.

2022-09-28 14:19 UTC, XavierChanth requested changes
Sorry @purnimavenkatasubbu , I think I missed one more, otherwise it looks great! Thanks so much!

2022-09-28 14:19 UTC, xavierchanth commented on content/docs/sdk/flutter/at_client_manager.md
> +  If client app's changes are ahead, it pushes the changes to the remote secondary.
`If client` -> `If the client`

2022-09-28 14:25 UTC, XavierChanth approved these changes

2022-09-29 06:07 UTC, merged