Fix link to Get Started page in Flutter introduction page
atsign-foundation/atsign.dev-3.0 pull request #173
Opened 2022-10-01 21:39 UTC by daniloff200

closes #172 

**- What I did**
Updated the ling

**- How I did it**
By changing path

**- How to verify it**
Just to check the page

**- Description for the changelog**
Fix broken link of Flutter intro page

2022-10-03 14:20 UTC, TylerTrott requested changes
Nice catch on finding the broken link but it looks like your fix does not work. You can test out your code by running 'npm install' and then 'npm run start'. Your redirect currently goes to /sdk/flutter/introduction/docs/start/flutter/

2022-10-03 14:35 UTC, daniloff200 commented
Hi, @TylerTrott 
Not sure, how it happened. The thing, that you've mentioned was before my fix, and, can be found on https://dev3.atsign.wtf/sdk/flutter/introduction/ 

I've tried my changes locally, and, it works fine.

[Untitled_ Oct 3, 2022 5_34 PM.webm](https://user-images.githubusercontent.com/13692220/193604228-65e79513-8a6c-4618-838d-d3eb7a08487b.webm)

2022-10-03 14:39 UTC, TylerTrott commented
> 

Hugo can be a little wonky. I think the easiest fix here is to check what the link address is on the page you want to be on, and simply copy and paste that address into the hyperlink.

2022-10-03 14:46 UTC, xavierchanth requested changes

2022-10-03 14:46 UTC, xavierchanth commented on content/docs/sdk/flutter/introduction.md
> +If you haven't already, we recommend you head to [Get Started Flutter Development](../../../start/flutter/) first.
Good catch with the URL error, however absolute path is preferred to relative URL. That way if this page moves, the URL will still be valid. `../../../` -> `/docs/`

2022-10-03 15:08 UTC, daniloff200 commented on content/docs/sdk/flutter/introduction.md
> +If you haven't already, we recommend you head to [Get Started Flutter Development](../../../start/flutter/) first.
@XavierChanth  I've reworked my change, but, with a `/docs` it also does not working

I've made it as `/start/flutter`

2022-10-03 15:46 UTC, TylerTrott approved these changes, later dismissed
/start/flutter/ works :) Looks good to me

2022-10-03 15:47 UTC, xavierchanth commented on content/docs/sdk/flutter/introduction.md
> +If you haven't already, we recommend you head to [Get Started Flutter Development](../../../start/flutter/) first.
My mistake, `/start/flutter` is the correct path

2022-10-03 15:48 UTC, XavierChanth approved these changes, later dismissed

2022-10-04 17:35 UTC, daniloff200 commented
guys, I have to fix the semantic check, but, dismissed your approvals @TylerTrott  @XavierChanth . Could you do that again, please?

2022-10-05 18:17 UTC, XavierChanth approved these changes

2022-10-05 19:09 UTC, merged

2022-10-30 22:43 UTC, JeremyTubongbanua commented
@daniloff200 
Hey! Thank you for your contribution. Your PR was accepted, merged, and it closed an issue. You could be eligible for a prize.

To be eligible, please send an email to [hacktoberfest@atsign.com](mailto:hacktoberfest@atsign.com) with a screenshot of the PR approval email. This is to prove that your email corresponds to the correct GitHub account. Thank you!

When it comes time to distribute the prizes, we will look at all the emails we've received from that email so don't forget to do this!