Fixed some typo and grammatical error in docs
atsign-foundation/atsign.dev-3.0 pull request #175
Opened 2022-10-02 17:58 UTC by HVbajoria

This pull request corrects some typos and grammatical mistakes in the docs. Fixes #158 

**- What I did**
I checked the files in the doc and found some typo and grammatical errors and corrected them.

**- How I did it**
I manually checked the files to find if there is any issue present.

**- Description for the changelog**
Fixed typos and grammatical errors

2022-10-03 10:48 UTC, cpswan requested changes
Hi @HVbajoria - thanks for the contribution. Mostly LGTM, but a couple of minor tweaks please.

2022-10-03 10:48 UTC, cpswan commented on content/docs/reference/synchronization.md
> +At the atProtocol, your data is encrypted with your self [encryption](/reference/encryption) key and stored on your device. Periodically, this data is copied securely over to a dedicated cloud server
s/At/With/

2022-10-03 10:48 UTC, cpswan commented on content/docs/reference/pricing-and-costs.md
> +Since the atPlatform is fully open-sourced and everyone can contribute, there is no cost for developers! When you make an app on the atPlatform, people that use your apps will not have to pay any fee
drop `to` before `commission`

2022-10-03 11:02 UTC, HVbajoria commented
Hi @cpswan, 
Sorry for the little errors. I have corrected them.
Could you please check once and let me know if there is more scope for improvement?
Will be more than happy to learn and incorporate.
Thank you

2022-10-03 12:45 UTC, cpswan requested changes

2022-10-03 12:45 UTC, cpswan commented on content/docs/reference/synchronization.md
This needs to be `With atProtocol` rather than `At atProtocol`

2022-10-03 12:45 UTC, cpswan commented
One down, one to go @HVbajoria

2022-10-03 12:51 UTC, HVbajoria commented
Sorry got it.
Made the changes. 
Could you please check now and help me correct if anything is still wrong @cpswan?
Happy to learn in the process. 
Thank you

2022-10-03 12:52 UTC, cpswan approved these changes

2022-10-03 12:52 UTC, merged

2022-10-03 12:52 UTC, cpswan commented
Thanks @HVbajoria

2022-10-03 12:54 UTC, HVbajoria commented
Thank you @cpswan 
Happy HacktoberFest!

2022-11-04 19:17 UTC, JeremyTubongbanua commented
@HVbajoria 
Hey! Thank you for your Hacktoberfest contribution. You could be eligible for a prize.

To be eligible, please send an email to [hacktoberfest@atsign.com](mailto:hacktoberfest@atsign.com) with a screenshot of the PR approval email (or just forward the PR approval email to us). This is to prove that your email corresponds to the correct GitHub account. Thank you!

When it comes time to distribute the prizes, we will look at all the emails we've received from that email so don't forget to do this!

2022-11-05 08:22 UTC, HVbajoria commented
Hey @JeremyTubongbanua,
Thank you for informing me. I have send a mail with the screenshot.
Thank you