Added Git Credentials in Footer and Open issue in Header
atsign-foundation/atsign.dev-3.0 pull request #182
Opened 2022-10-04 17:15 UTC by PriyanshuRj

**- What I did**
fixes #22 
I created a Link to open an issue on the atsign documentation repository and added details for the last commit in the footer as specified.
`Last updated on <date>`
`By <author> in <short commit id>`  (commit id can link to the commit in GitHub)
**- How I did it**

**- How to verify it**
After running the Documentation site on localhost, you can check the header and the footer of the site to verify the same.
![image](https://user-images.githubusercontent.com/76838551/193883887-0c9588cc-7161-4351-9e14-2f17bbd2bdf8.png)
![image](https://user-images.githubusercontent.com/76838551/193883831-3b2c43ef-895c-409e-8ae7-1d27ddb30d0a.png)

**- Description for the changelog**
Updated the header of the site to add a open issue features and added details of last commit in the footer.

2022-10-05 18:38 UTC, XavierChanth requested changes
Hi @PriyanshuRj, thanks for your solution. There are a few more improvements I would like to see included in your solution:

1. This solution is only able to get the latest commit on the repo, It would be nice to see this information based on the page that you are on. Most times, the page that you are viewing will not have been modified in the last commit.
2. I would rather this information be part of the hugo build process, this would allow this information to be served statically instead of through a client side script (much faster loads and no unnecessary api calls to GitHub).

It may be helpful to see what kind of Git information is already included in Hugo: https://gohugo.io/variables/git/#readout.

2022-10-05 18:38 UTC, XavierChanth commented on layouts/partials/main/footer.html
> -            <img class="toggle-light" src="{{ .RelPermalink }}" width="124em">
Please avoid introducing unnecessary formatting changes.

2022-10-06 16:00 UTC, PriyanshuRj commented on layouts/partials/main/footer.html
> -            <img class="toggle-light" src="{{ .RelPermalink }}" width="124em">
Okay sorry for the same

2022-10-07 10:16 UTC, PriyanshuRj commented
New Look after adapting to Hugo .GitInfo
![image](https://user-images.githubusercontent.com/76838551/194531072-0cbb7e04-afda-43e7-9d09-a5774334e129.png)

2022-10-07 15:41 UTC, XavierChanth requested changes
Looks good, but to avoid code duplication please put your work into the main/footer partial.
The file is at `layouts/partials/main/footer.html`

2022-10-08 18:18 UTC, PriyanshuRj commented
> Looks good, but to avoid code duplication please put your work into the main/footer partial. The file is at `layouts/partials/main/footer.html`

Actually, the git variables are not accessible in the partials so we need to pass them down which will also create extra code.

2022-10-08 18:50 UTC, XavierChanth commented
> > Looks good, but to avoid code duplication please put your work into the main/footer partial. The file is at `layouts/partials/main/footer.html`
> 
> Actually, the git variables are not accessible in the partials so we need to pass them down which will also create extra code.

Ah you are correct, the partial call doesn't have the context being passed down.
You can in pass down a `.` for everything, or just the Git variable context.

>One of the most common mistakes with new Hugo users is failing to pass a context to the partial call. In the pattern above, note how “the dot” (.) is required as the second argument to give the partial context. You can read more about “the dot” in the [Hugo templating introduction](https://gohugo.io/templates/introduction/).  
Source: https://gohugo.io/templates/partials/#use-partials-in-your-templates

This partial didn't have the context being passed, since it didn't need it prior to now.

2022-10-09 15:09 UTC, PriyanshuRj commented
> is failing to pass a context to the partial call. In the pattern above,

ok got it thanks

2022-10-09 15:09 UTC, PriyanshuRj commented
> > > Looks good, but to avoid code duplication please put your work into the main/footer partial. The file is at `layouts/partials/main/footer.html`
> > 
> > 
> > Actually, the git variables are not accessible in the partials so we need to pass them down which will also create extra code.
> 
> Ah you are correct, the partial call doesn't have the context being passed down. You can in pass down a `.` for everything, or just the Git variable context.
> 
> > One of the most common mistakes with new Hugo users is failing to pass a context to the partial call. In the pattern above, note how “the dot” (.) is required as the second argument to give the partial context. You can read more about “the dot” in the [Hugo templating introduction](https://gohugo.io/templates/introduction/).
> > Source: https://gohugo.io/templates/partials/#use-partials-in-your-templates
> 
> This partial didn't have the context being passed, since it didn't need it prior to now.

Thanks got it.

2022-10-10 16:53 UTC, XavierChanth approved these changes

2022-10-10 16:57 UTC, TylerTrott approved these changes

2022-10-10 16:58 UTC, merged

2022-10-12 17:02 UTC, JeremyTubongbanua commented
Amazing work @PriyanshuRj :)