ci:
atsign-foundation/atsign.dev-3.0 pull request #255
Opened 2023-01-10 18:52 UTC by JeremyTubongbanua

## What I did

Created `CI.yaml` in `workflows/` that runs the following upon a `push` and/or `pull request` to trunk:

- npm ci (clean install)
- npm run build
- npm run build:staging

2023-01-10 20:55 UTC, XavierChanth approved these changes

2023-01-10 20:58 UTC, XavierChanth requested changes

2023-01-10 20:58 UTC, XavierChanth commented on .github/workflows/CI.yaml
> +      - name: build
We don't need to build before calling build:staging, maybe instead use a matrix to test a build:staging and a build:production in parallel?

2023-01-10 20:59 UTC, XavierChanth commented
The other check we need to do here is make sure the css isn't overpurged.
Maybe we can check the contents/length of hugo_stats.json after running the build.

2023-01-11 19:08 UTC, XavierChanth approved these changes
LGTM

2023-01-11 19:14 UTC, JeremyTubongbanua commented
Ready to merge @XavierChanth

2023-01-11 19:20 UTC, merged