Added more content to encryption, public and private keys as well as …
atsign-foundation/atsign.dev-3.0 pull request #46
Opened 2022-06-09 22:06 UTC by Jesseadriano10

…fixed privacy lead too long issue. Also changed the short-code to fix issue where image looked stretched. Lastly, fixed issue where single page image was in asset folder.

**- What I did**
- Added more content that related with how AtSign implemented encryption and keys.
- Removed mistake where the lead for the privacy page was too long with a shorter sentence.
- I changed the short code for the *image.html* document to use img-contain which prevents an issue with unbounded images.
- 
**- How I did it**

See screenshots below:
![image](https://user-images.githubusercontent.com/34658202/172952413-2e9ec719-7989-4b94-8711-3ade2c647719.png)
![image](https://user-images.githubusercontent.com/34658202/172952489-44894424-2759-46e1-b25b-f702dc557f46.png)
![image](https://user-images.githubusercontent.com/34658202/172952552-553d82ee-1915-43da-9ace-197f58e2bc2b.png)

- I removed the directory from assets and made a new folder for the content in public_private_keys where the image should be.
- Lastly, I stopped using the showcase card shortcode and applied img-contain to the image shortcode which fixed the issue.

**- How to verify it**
- See screenshots to double check that content is up to date with website. 
- Check directory folder in assets to make sure that E2EE.png is gone.
- The image in public_private_keys should look normal now and not stretched.

**- Description for the changelog**

2022-06-09 22:36 UTC, XavierChanth requested changes
Overall good content, please see the changes I requested.

If you want some more reference information see [this document](https://docs.google.com/document/d/14PZ-FHV9djBJL1RR8G8aYd6qxiWErBJEvRW9hD0pfNQ/edit?pli=1) (page 6)

2022-06-09 22:36 UTC, XavierChanth commented on content/docs/reference/public_private_keys/index.md
> +  <em>Providing access to information</em>
Try to keep frontmatter consistent, one lead is italicized, the other isn't. I would say don't italicize.

2022-06-09 22:36 UTC, XavierChanth commented on content/docs/reference/public_private_keys/index.md
> +toc: false # Change this to "true" to show the table of contents
The other page has toc enabled, I would enable it here as well since this page seems longer.

2022-06-09 22:36 UTC, XavierChanth commented on content/docs/reference/encryption.md
> +### Related Sources
Nice touch adding related sources :)

Please change this to `##`

2022-06-09 22:36 UTC, XavierChanth commented on content/docs/reference/public_private_keys/index.md
> +On the other hand, public keys are distributed to the trusted masses. This is done through a public-key distribution channel. This channel should provide authentication and integrity. Someone should
I suggest using [Alice and Bob](https://en.wikipedia.org/wiki/Alice_and_Bob) as the traditional example.

2022-06-09 22:36 UTC, XavierChanth commented on content/docs/reference/public_private_keys/index.md
> +    - Internal keys start with an underscore(_) and are not displayed in scan results. Internal keys can be looked up only by the owner of the secondary
`can be looked up only by` > `can only be looked up by`

2022-06-09 22:36 UTC, XavierChanth commented on content/docs/reference/public_private_keys/index.md
> +{{< image class="bg-white" src="E2EE.png" type="page"  >}}
I suggest putting this image under the `## Definition` section.

2022-06-09 22:36 UTC, XavierChanth commented on content/docs/reference/public_private_keys/index.md
> +A key in the @protocol can be formed by using any alphanumeric and special characters (UTF-8) excluding "@", ":" and a white space (" "). A key in a secondary can be any of the following 5 types:
Mention that this is often referred to as an `AtKey`

2022-06-09 22:36 UTC, XavierChanth commented on content/docs/reference/public_private_keys/index.md
> +2. Private Key
Please change this to be called [Self Key](https://github.com/atsign-foundation/at_tools/blob/trunk/at_commons/lib/src/keystore/at_key.dart#L88-L104)

2022-06-09 22:36 UTC, XavierChanth commented on content/docs/reference/public_private_keys/index.md
> +3. User key
Please change this to be called [Shared Key](https://github.com/atsign-foundation/at_tools/blob/trunk/at_commons/lib/src/keystore/at_key.dart#L62-L86)

2022-06-09 22:36 UTC, XavierChanth commented on content/docs/reference/public_private_keys/index.md
> +4. Internal Key
Please change this to be called [Private Key](https://github.com/atsign-foundation/at_tools/blob/trunk/at_commons/lib/src/keystore/at_key.dart#L106-L120)

2022-06-09 22:36 UTC, XavierChanth commented on content/docs/reference/public_private_keys/index.md
> +A private key is used in asymmetric key cryptography. Asymmetric key cryptography is based on applying mathematical functions to numbers to achieve personal secrecy. It uses two keys, one being the p
If you can think of an analogy that fits a little better, that would be great, if not, don't spend too much time on it.

2022-06-09 22:36 UTC, XavierChanth commented on content/docs/reference/encryption.md
> +### How we do it
Change this to `##`

2022-06-10 00:08 UTC, JeremyTubongbanua requested changes
See requested changes

2022-06-10 00:08 UTC, JeremyTubongbanua commented on layouts/shortcodes/image.html
> +        <img class="img-contain {{$class}}" src="{{ $image.RelPermalink }}" width="{{ $image.Width }}" height="{{ $image.Height }}">
Nice addition!

2022-06-10 00:08 UTC, JeremyTubongbanua commented on content/docs/reference/public_private_keys/index.md
> +{{< image class="bg-white" src="E2EE.png" type="page"  >}}
`{{< image class="bg-white" src="img/reference/E2EE.png" type="asset"  >}}`

?

2022-06-10 00:12 UTC, JeremyTubongbanua requested changes
Also

Is there a reason why we're moving images back from the assets folder?

2022-06-10 00:18 UTC, JeremyTubongbanua approved these changes
Nice work

2022-06-10 01:00 UTC, JeremyTubongbanua requested changes
Maybe use `-` instead of `_`

Rename  `public_private_keys` to `public-private-keys` to keep the URL paths consistent (just like how we have `root-server.md` and `secondary-server.md`)

2022-06-10 12:58 UTC, XavierChanth approved these changes
lgtm

2022-06-10 13:08 UTC, JeremyTubongbanua approved these changes
Nice work @Jesseadriano10

2022-06-10 17:19 UTC, merged