definition for polymorphism
atsign-foundation/atsign.dev-3.0 pull request #60
Opened 2022-06-15 01:29 UTC by L1AMcB

**- What I did**
Added the definition of polymorphism
**- How I did it**
created branch and used cherry pick function
**- How to verify it**
read it and let me know what you think
**- Description for the changelog**
Added definition for polymorphism

2022-06-15 01:30 UTC, L1AMcB commented
I don't have how polymorphism is used within assign, just the definition and an example for now.

2022-06-15 01:31 UTC, JeremyTubongbanua requested changes
This might be what we want for Polymorphism

https://atsign.dev/docs/get-started/understand-the-platform/polymorphism/

2022-06-15 15:56 UTC, xavierchanth commented
> This might be what we want for Polymorphism
> 
> https://atsign.dev/docs/get-started/understand-the-platform/polymorphism/

Correct, we want Atsign's definition for polymorphism for this one. You could even start with a dictionary definition and expand upon it in the context of our tech.

2022-06-15 19:14 UTC, JeremyTubongbanua commented
Good work so far! Maybe you could relate it to namespaces because I believe namespaces and polymorphism are related.

2022-06-15 20:50 UTC, Jesseadriano10 requested changes
* It would be good to include the Polymorphic Data header from the article into the definition.
* Also, I would add a breadcrumb card on the related sources.

Other than that, it is looking good to me!

2022-06-15 21:19 UTC, XavierChanth commented
Beyond @Jesseadriano10 's requested changes, LGTM

2022-06-16 00:39 UTC, XavierChanth requested changes
I believe the headings used in other pages are `##`, please double check that.

2022-06-16 00:39 UTC, XavierChanth commented on content/docs/reference/polymorphism.md
> +We can even take things one step further: the [@buzz app](https://atsign.com/apps/buzz/) is a stellar example of polymorphic data on the @platform. @buzz is like your contacts application, but with a
You can probably remove the "We can even take things one step further:"

2022-06-16 14:52 UTC, xavierchanth approved these changes
LGTM

2022-06-16 19:01 UTC, JeremyTubongbanua approved these changes
Good work!

2022-06-16 19:03 UTC, Jesseadriano10 approved these changes
Nice Job Liam!

2022-06-16 19:19 UTC, merged