Notification definition
atsign-foundation/atsign.dev-3.0 pull request #64
Opened 2022-06-15 22:31 UTC by JeremyTubongbanua

**- What I did**
Start on notification info.
Feel free to give feedback on this page. A little bit lost with this definition!

**- How I did it**
See files changed

**- How to verify it**
![image](https://user-images.githubusercontent.com/79019866/173942954-9144997f-1ca5-47b9-a350-8e3f05f85506.png)

2022-06-15 22:53 UTC, JeremyTubongbanua commented
I don't know if there's much more to say about **Notification**. We will dive more into code stuff in another section of the dev site.

2022-06-16 00:24 UTC, XavierChanth requested changes

2022-06-16 00:24 UTC, xavierchanth commented on content/docs/reference/notification.md
>      Definition of Notificaton in the @platform
Clean up the lead and expand upon description please

2022-06-16 00:24 UTC, xavierchanth commented on content/docs/reference/notification.md
> +`notify:((?<operation>update|delete):)?(ttl:(?<ttl>\d+):)?(ttb:(?<ttb>\d+):)?(ttr:(?<ttr>(-)?\d+):)?(ccd:(?<ccd>true|false):)?(@(?<forAtSign>[^@:\s]-)):(?<atKey>[^:]((?!:{2})[^@])+)@(?<atSign>[^@:\s]
Can you break down and explain this regex please, that will be more useful to readers than just providing it.

2022-06-17 01:22 UTC, JeremyTubongbanua commented on content/docs/reference/notification.md
> +`notify:((?<operation>update|delete):)?(ttl:(?<ttl>\d+):)?(ttb:(?<ttb>\d+):)?(ttr:(?<ttr>(-)?\d+):)?(ccd:(?<ccd>true|false):)?(@(?<forAtSign>[^@:\s]-)):(?<atKey>[^:]((?!:{2})[^@])+)@(?<atSign>[^@:\s]
See 3c7f10af673287485c2422bdfc7556b9d58ef49e

Little stuck on the AtKey details regex part (I need examples there too)

2022-06-17 01:22 UTC, JeremyTubongbanua commented on content/docs/reference/notification.md
>      Definition of Notificaton in the @platform
See 3c7f10af673287485c2422bdfc7556b9d58ef49e

2022-06-17 02:30 UTC, JeremyTubongbanua commented on content/docs/reference/notification.md
> +`notify:((?<operation>update|delete):)?(ttl:(?<ttl>\d+):)?(ttb:(?<ttb>\d+):)?(ttr:(?<ttr>(-)?\d+):)?(ccd:(?<ccd>true|false):)?(@(?<forAtSign>[^@:\s]-)):(?<atKey>[^:]((?!:{2})[^@])+)@(?<atSign>[^@:\s]
@TylerTrott

2022-06-17 02:41 UTC, XavierChanth commented on content/docs/reference/notification.md
> +`notify:((?<operation>update|delete):)?(ttl:(?<ttl>\d+):)?(ttb:(?<ttb>\d+):)?(ttr:(?<ttr>(-)?\d+):)?(ccd:(?<ccd>true|false):)?(@(?<forAtSign>[^@:\s]-)):(?<atKey>[^:]((?!:{2})[^@])+)@(?<atSign>[^@:\s]
See if parts of the doc I just sent you help @JeremyTubongbanua

2022-06-19 19:31 UTC, JeremyTubongbanua commented
I think this is right? c3ed93e34877935109d024bcdee45ac6908fcc56

2022-06-20 23:39 UTC, XavierChanth approved these changes

2022-06-20 23:53 UTC, merged